export * from './cau-hoi.dto';
export * from './cau-tra-loi.dto';
export * from './chi-tiet-de-thi.dto';
export * from './de-thi.dto';
export * from './files.dto';
export * from './khoa.dto';
export * from './mon-hoc.dto';
export * from './phan.dto';
export * from './user.dto';
export * from './yeu-cau-rut-trich.dto';
export * from './clo.dto';

// New English-named DTOs
export * from './departments.dto';
export * from './subjects.dto';
export * from './sections.dto';
export * from './questions.dto';
export * from './answers.dto';
export * from './exams.dto';
export * from './exam-questions.dto';
export * from './extraction-requests.dto';
